---
kind: pipeline
type: docker
name: node-16

steps:
  - name: build & test
    image: node:16-alpine
    commands:
      - npm ci
      - npm run build --if-present
      - npm test

---
kind: pipeline
type: docker
name: node-18

steps:
  - name: build & test
    image: node:18-alpine
    commands:
      - npm ci
      - npm run build --if-present
      - npm test
